FROM node:18.12.1-alpine3.16 AS builder
ARG NEXT_PUBLIC_BMCONNECTAPI_URL_DEPOSITO_ARG
ARG NEXT_PUBLIC_BMCONNECTAPI_URL_GERENCIAL_ARG
ARG NEXT_PUBLIC_BMCONNECTAPI_URL_TAREFAS_ARG
ARG NEXT_PUBLIC_BMCONNECTAPI_URL_EXTRATO_ARG
ARG NEXT_PUBLIC_BMCONNECTAPI_URL_FINANCIAL_ARG
ENV NEXT_PUBLIC_BMCONNECTAPI_URL_DEPOSITO=$NEXT_PUBLIC_BMCONNECTAPI_URL_DEPOSITO_ARG
ENV NEXT_PUBLIC_BMCONNECTAPI_URL_GERENCIAL=$NEXT_PUBLIC_BMCONNECTAPI_URL_GERENCIAL_ARG
ENV NEXT_PUBLIC_BMCONNECTAPI_URL_TAREFAS=$NEXT_PUBLIC_BMCONNECTAPI_URL_TAREFAS_ARG
ENV NEXT_PUBLIC_BMCONNECTAPI_URL_EXTRATO=$NEXT_PUBLIC_BMCONNECTAPI_URL_EXTRATO_ARG
ENV NEXT_PUBLIC_BMCONNECTAPI_URL_FINANCIAL=$NEXT_PUBLIC_BMCONNECTAPI_URL_FINANCIAL_ARG
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

# ---

FROM node:18.12.1-alpine3.16 AS runner

ARG NEXT_PUBLIC_BMCONNECTAPI_URL_DEPOSITO_ARG
ARG NEXT_PUBLIC_BMCONNECTAPI_URL_GERENCIAL_ARG
ARG NEXT_PUBLIC_BMCONNECTAPI_URL_TAREFAS_ARG
ARG NEXT_PUBLIC_BMCONNECTAPI_URL_EXTRATO_ARG
ARG NEXT_PUBLIC_BMCONNECTAPI_URL_FINANCIAL_ARG

ENV NEXT_PUBLIC_BMCONNECTAPI_URL_DEPOSITO=$NEXT_PUBLIC_BMCONNECTAPI_URL_DEPOSITO_ARG
ENV NEXT_PUBLIC_BMCONNECTAPI_URL_GERENCIAL=$NEXT_PUBLIC_BMCONNECTAPI_URL_GERENCIAL_ARG
ENV NEXT_PUBLIC_BMCONNECTAPI_URL_TAREFAS=$NEXT_PUBLIC_BMCONNECTAPI_URL_TAREFAS_ARG
ENV NEXT_PUBLIC_BMCONNECTAPI_URL_EXTRATO=$NEXT_PUBLIC_BMCONNECTAPI_URL_EXTRATO_ARG
ENV NEXT_PUBLIC_BMCONNECTAPI_URL_FINANCIAL=$NEXT_PUBLIC_BMCONNECTAPI_URL_FINANCIAL_ARG
WORKDIR /app
COPY --from=builder /app/src ./src
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./next.config.js
COPY --from=builder /app/babel.config.js ./babel.config.js
COPY --from=builder /app/tsconfig.json ./tsconfig.json
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 3000
CMD ["yarn", "start"]
